### ISSUE TITLE
SPIFFS hangs during uploading?

### ISSUE THREAD

**Issue by Rickgg** [esp8266/arduino-esp8266fs-plugin#13]
When I try to flash the files, the SPIFFS uploader "hangs" and stops transmitting. I'm using Arduino IDE 1.6.5 and Mac OS X Yosemite. Any ideas as to why this could be happening?

**Comment by kaeferfreund** [comment]
same here

**Comment by me-no-dev** [comment]
what USB to UART are you guys using? I had tons of problems with FTDI
what size SPIFFS?

**Comment by kaeferfreund** [comment]
64k SPIFFS with FTDI converter. But the FTDI works quite fine with everything else...
Trying a CH340 later on

**Comment by me-no-dev** [comment]
issue with ftdi comes when it transmits a lot of 0xFF which is EMPTY byte in the flash, because the signal  looks constant and it thinks that the connection failed. For the sketch a patch was added to esptool to pad the firmware (the space between the bootloader and the firmware) with 0x55 instead to transmit pulses and not fail sketch upload.

**Comment by me-no-dev** [comment]
You can move to 1.5.7+ and use OTA to upload SPIFFS images much faster and reliable :)
The issue seem to not exist on ElCapitan but the FTDI needs to be behind USB hub in order to work (changes in the USB stack from Apple broke some drivers)

**Comment by kaeferfreund** [comment]
thx me-no-dev, just waiting for my esp-12 to arrive, bec. the esp-01 doesn't have enough space for ota updating.

**Comment by Rickgg** [comment]
How do you upload SPIFFS files through OTA? I didn't find any instructions in the docs.

**Comment by Rickgg** [comment]
Found it! should have looked a little bit harder... hehehe :grin:
